[package]
name = "nonzero"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
num-traits = "0.2.14"
proc-macro2 = "1.0.28"
quote = "1.0.9"
syn = "1.0.74"
